import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { getDatabase, onValue, ref } from "firebase/database";
@Component({
  selector: 'app-all-notes',
  templateUrl: './all-notes.page.html',
  styleUrls: ['./all-notes.page.scss'],
})
export class AllNotesPage implements OnInit {
notes :any = [];
  name: any;
  constructor(private router:Router) { }

  ngOnInit() {
    const database = getDatabase();
    const starCountRef = ref(database, 'notes',);
  
    onValue(starCountRef, (snapshot) => {
      const data = snapshot.val();
      this.notes = Object.values(data); 
     
  })
  }
  clicknote(name:string){
    this.router.navigate(['/tabs/tab1/chaque-note',name])
  }
  get note() {
    console.log( this.notes.find((p:any)=> p.nom == this.name));
    return this.notes.find((p:any)=> p.nom == this.name)
  }
  

//   notes:any[]=[
//     {
//     "name":"Pamplemousse",
//     "notes":"/assets/note/27.png"
//   },
//   {
//     "name":"Gingembre",
//     "notes":"/assets/note/18.png"
//   },
//   {
//     "name":"Citron",
//     "notes":"/assets/note/19.png"
//   },
//   {
//     "name":"Menthe",
//     "notes":"/assets/note/21.png"
//   },
//   {
//     "name":"Poivre rose",
//     "notes":"/assets/note/6.png"
//   },
//   {
//     "name":"Noix de muscade",
//     "notes":"/assets/note/23.png"
//   },
//   {
//     "name":"Jasmin",
//     "notes":"/assets/note/22.png"
//   },
//   {
//     "name":"Encens",
//     "notes":"/assets/note/20.png"
//   },
//   {
//     "name":"Vétiver",
//     "notes":"/assets/note/17.png"
//   },
//   {
//     "name":"Cèdre",
//     "notes":"/assets/note/24.png"
//   },
//   {
//     "name":"Bois de santal",
//     "notes":"/assets/note/10.png"
//   },
//   {
//     "name":"Patchouli",
//     "notes":"/assets/note/4.png"
//   },
//   // 
//   {
//     "name":"pomme",
//     "notes":"/assets/note/28.png"
//   },
//   {
//     "name":"Cerise noire",
//     "notes":"/assets/note/29.png"
//   }, 
//   {
//     "name":"Basilic",
//     "notes":"/assets/note/30.png"
//   }, 
//   {
//     "name":"Ciste",
//     "notes":"/assets/note/31.png"
//   }, 
//   {
//     "name":" Cassis",
//     "notes":"/assets/note/32.png"
//   }, 
//   {
//     "name":"Lavande",
//     "notes":"/assets/note/33.png"
//   }, 
//   // {
//   //   "name":"Lis",
//   //   "notes":"/assets/note/34.png"
//   // }, 


//   ]
  
//   products: any[] =[
//     {"id": 1,
//     "name" : "Bleu De Chanel",
//     "image": "/assets/pr/bleu de chanel (4).jpg",
//     "topnotename":"Lemon",
//     "topnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//     "herat-name":"Noix de muscade",
//     "heratnote":"/assets/notes/Noix de muscade.jpg",
//     "base-name":"Bois de santal",
//     "basenote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
    
//   },
//   {"id": 2,
//   "name" : "Chanel n°05",
//   "image": "/assets/pr/_Chanel_N05-.jpg",
//   "top note-name":"Lemon",
//   "topnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//   "herat-name":"Muguet",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
//   {"id": 3,
//   "name" : "Chanel Egoïste",
//   "image": "/assets/pr/CHANEL_ÉGOÏSTE.jpg",
//   "topnotename":"Acajou",
//   "topnote":"/assets/notes/Les bois_ l’Acajou - Astuces Pratiques.jpg",
//   "herat-name":"Œillet",
//   "heratnote":"/assets/notes/œillet-removebg-preview.jpg",
//   "base-name":"Vanille",
//   "basenote":"/assets/notes/Vanille - Fleurs Comestibles - Épices d'exception.jpg",
//   },
//   {"id": 4,
//   "name" : "Chanel Chance",
//   "image": "/assets/pr/Chanel_CHANCE_P.jpg",
//   "topnotename":"Poivre rose",
//   "topnote":"/assets/notes/Cet article n'est pas disponible _ Etsy.jpg",
//   "herat-name":"Lemon",
//   "heratnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//   "base-name":"Vanille",
//   "basenote":"/assets/notes/Vanille - Fleurs Comestibles - Épices d'exception.jpg",
//   },
//   {"id": 5,
//   "name" : "ChanelEau Tendre",
//   "image": "/assets/pr/Chance_Eau_Tend.jpg",
//   "topnotename":"Pamplemousse",
//   "topnote":"/assets/notes/Vinaigrette au pamplemousse (1).jpg",
//   "herat-name":"Jasmine",
//   "heratnote":"/assets/notes/581f87d8-87b4-4f4f-8789-aaf78f6a68e4.jpg",
//   "base-name":"Iris",
//   "basenote":"/assets/notes/Rachel_Levy_-_Other_botanicals__2013-2016_-removebg-preview.jpg",
//   },
//   {"id": 6,
//   "name" : "Dior Sauvage",
//   "image": "/assets/pr/Sauva.jpg",
//   "topnotename":"Poivre",
//   "topnote":"/assets/notes/Poivre_noir_entier_IGP_Kampot_-_achat__recettes_et_bienfaits-removebg-preview.jpg",
//   "herat-name":"Patchouli",
//   "heratnote":"/assets/notes/Patchouli Essential Oil - 1 oz _ Dropper Bottle _ I want to create a blend (add scents to additional comments box below).jpg",
//   "base-name":"Ciste",
//   "basenote":"/assets/notes/Ciste - Cistus _ plantation, floraison et conseils d'entretien.jpg",
//   },
//   {"id": 7,
//   "name" : "Dior Bois D'argent",
//   "image": "/assets/pr/Bois_D_Argent__La_Collection_by_Christian_Dior_-removebg-preview.jpg",
//   "topnotename":"Iris",
//   "topnote":"/assets/notes/African Iris White  BULK SALE read Description - Etsy.jpg",
//   "herat-name":"Patchouli",
//   "heratnote":"/assets/notes/Patchouli Essential Oil - 1 oz _ Dropper Bottle _ I want to create a blend (add scents to additional comments box below).jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
//   {"id": 8,
//   "name" : "Dior AmbreNuit",
//   "image": "/assets/pr/Holiday_Gift_Idea___Dior_US-removebg-preview.jpg",
//   "topnotename":"Pamplemousse",
//   "topnote":"/assets/notes/Vinaigrette au pamplemousse (1).jpg",
//   "herat-name":"Poivre rose",
//   "heratnote":"/assets/notes/Cet article n'est pas disponible _ Etsy.jpg",
//   "base-name":"Patchouli",
//   "basenote":"/assets/notes/Patchouli Essential Oil - 1 oz _ Dropper Bottle _ I want to create a blend (add scents to additional comments box below).jpg",
//   },
//   {"id": 9,
//   "name" : "Armani withYou",
//   "image": "/assets/pr/Emporio_Armani.jpg",
//   "topnotename":"Poivre rose",
//   "topnote":"/assets/notes/Cet article n'est pas disponible _ Etsy.jpg",
//   "herat-name":"Cannelle",
//   "heratnote":"/assets/notes/Cannelle___bienfaits__propriétés_et_effets_secondaires-removebg-preview.jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
  
//   {"id": 10,
//   "name" : "Dior Fahrenheit",
//   "image": "/assets/pr/Dior_Fahrenheit.jpg",
//   "topnotename":"Lemon",
//   "topnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//   "herat-name":"Muguet",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
//   {"id": 11,
//   "name" : "Yves Saint Libre",
//   "image": "/assets/pr/L__039_Homme_Libre_Cologne_Tonic_Yves_Saint_Laurent_Colônia_-_a_fragrância_Masculino_2013-removebg-preview.jpg",
//   "topnotename":"Bergamote",
//   "topnote":"/assets/notes/Attract Abundance with Soothing Bergamot (Citrus Bergamia) - Goddess Witchcraft.jpg",
//   "herat-name":"Muguet",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
//   {"id": 12,
//   "name" : "bleu electrique",
//   "image": "/assets/pr/Yves Saint Laurent La Nuit De L'homme _Bleu Electrique_ for Men - EDT - 100ml.jpg",
//   "topnotename":"Bergamote",
//   "topnote":"/assets/notes/Attract Abundance with Soothing Bergamot (Citrus Bergamia) - Goddess Witchcraft.jpg",
//   "herat-name":"Géranium",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Vétiver",
//   "basenote":"/assets/notes/What Does Vetiver Smell Like_ The Ultimate Guide _ Dapper Confidential.jpg",
//   },
//   {"id": 13,
//   "name" : "Armani amber",
//   "image": "/assets/pr/Giorgio_Armani.jpg",
//   "topnotename":"Ambre",
//   "topnote":"/assets/notes/Amber-removebg-preview.jpg",
//   "herat-name":"Vanille ",
//   "heratnote":"/assets/notes/Vanille - Fleurs Comestibles - Épices d'exception.jpg",
//   "base-name":"Lavender",
//   "basenote":"/assets/notes/2007_04_07_Une_fleur_de_jacinthe-removebg-preview.jpg",
//   },
//   {"id": 14,
//   "name" : "Creed aventus",
//   "image": "/assets/pr/Creed_Aventus.jpg",
//   "topnotename":"Poivre rose",
//   "topnote":"/assets/notes/Cet article n'est pas disponible _ Etsy.jpg",
//   "herat-name":"Ananas ",
//   "heratnote":"/assets/notes/Pineapple_tropical_fruit_or_ananas_isolated_on_white_background_cutout-removebg-preview.jpg",
//   "base-name":"Musc",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   },
//   {"id": 15,
//   "name" : "Creed himalaya",
//   "image": "/assets/pr/Millesime.jpg",
//   "topnotename":"Pamplemousse",
//   "topnote":"/assets/notes/Vinaigrette au pamplemousse (1).jpg",
//   "herat-name":"Bois de santal",
//   "heratnote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
//   "base-name":"Musc",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   },
//   {"id": 16,
//   "name" : " Creed water",
//   "image": "/assets/pr/Creed_Silver.jpg",
//   "topnotename":"Mandarine",
//   "topnote":"/assets/notes/15_Kg_Mandarines_Clementines_NULETA_en_6_malles-removebg-preview.jpg",
//   "herat-name":"Cassis",
//   "heratnote":"/assets/notes/Confiture de cassis (2).jpg",
//   "base-name":"Musc",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   },
//   {"id": 17,
//   "name" : "Nishane hacivat",
//   "image": "/assets/pr/Hacivat_Nishane.jpg",
//   "topnotename":"Ananas",
//   "topnote":"/assets/notes/Pineapple_tropical_fruit_or_ananas_isolated_on_white_background_cutout-removebg-preview.jpg",
//   "herat-name":"Patchouli",
//   "heratnote":"/assets/notes/Patchouli Essential Oil - 1 oz _ Dropper Bottle _ I want to create a blend (add scents to additional comments box below).jpg",
//   "base-name":"Mousse de chêne",
//   "basenote":"/assets/notes/Carrelage mural hexagonal en mousse de renne - Vert mousse - 22Cm↕ _ ↔25Cm (1).jpg",
//   },
//   {"id": 18,
//   "name" : "Nishane shem",
//   "image": "/assets/pr/SHEM_Nishane.jpg",
//   "topnotename":"Géranium",
//   "topnote":"/assets/notes/New_Seeds_for_2024-removebg-preview.jpg",
//   "herat-name":"Ambre",
//   "heratnote":"/assets/notes/Amber-removebg-preview.jpg",
//   "base-name":"Vétiver",
//   "basenote":"/assets/notes/What Does Vetiver Smell Like_ The Ultimate Guide _ Dapper Confidential.jpg",
//   },
//   {"id": 19,
//   "name" : "Soleil neige",
//   "image": "/assets/pr/TOM_FORD_Soleil_.jpg",
//   "topnotename":"Bergamote",
//   "topnote":"/assets/notes/Attract Abundance with Soothing Bergamot (Citrus Bergamia) - Goddess Witchcraft.jpg",
//   "herat-name":"Jasmine",
//   "heratnote":"/assets/notes/581f87d8-87b4-4f4f-8789-aaf78f6a68e4.jpg",
//   "base-name":"Ciste",
//   "basenote":"/assets/notes/Ciste - Cistus _ plantation, floraison et conseils d'entretien.jpg"
//   },
//   {"id": 20,
//   "name" : "Black orchid",
//   "image": "/assets/pr/TOM_Ford_Black_Black_Orchid.jpg",
//   "topnotename":"Ylang-ylang",
//   "topnote":"/assets/notes/Ylang Ylang Essential Oil - 100ml.jpg",
//   "herat-name":"Jasmine",
//   "heratnote":"/assets/notes/581f87d8-87b4-4f4f-8789-aaf78f6a68e4.jpg",
//   "base-name":"Vétiver",
//   "basenote":"/assets/notes/What Does Vetiver Smell Like_ The Ultimate Guide _ Dapper Confidential.jpg"
//   },
//   {"id": 21,
//   "name" : "Beau du jour",
//   "image": "/assets/pr/TOM_FORD_Beau_de_Jour_eau.jpg",
//   "topnotename":"",
//   "topnote":"/assets/notes/",
//   "herat-name":"Jasmine",
//   "heratnote":"/assets/notes/",
//   "base-name":"Vétiver",
//   "basenote":"/assets/notes/",
//   },
//   {"id": 22,
//   "name" : "Fucking fabulous",
//   "image": "/assets/pr/Fucking_Fabulous_-_TOM_FORD___Sephora-removebg-preview.jpg",
//   "topnotename":" Lavender",
//   "topnote":"/assets/notes/2007_04_07_Une_fleur_de_jacinthe-removebg-preview.jpg",
//   "herat-name":"Vanille",
//   "heratnote":"/assets/notes/Vanille - Fleurs Comestibles - Épices d'exception.jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
 
//   },
//   {"id": 23,
//   "name" : "Lost cherry",
//   "image": "/assets/pr/TOM_FORD_Private_Blendw.jpg",
//   "topnotename":" Cerise noire",
//   "topnote":"/assets/notes/Bouchées gourmandes cerise-chocolat _ Découvrez nos recettes (1).jpg",
//   "herat-name":"Griotte",
//   "heratnote":"/assets/notes/Crème brûlées aux griottes (1).jpg",
//   "base-name":"Vétiver",
//   "basenote":"/assets/notes/What Does Vetiver Smell Like_ The Ultimate Guide _ Dapper Confidential.jpg",
//   },
//   {"id": 24,
//   "name" : "",
//   "image": "/assets/pr/Bitter peach",
//   "topnotename":" Cerise noire",
//   "topnote":"/assets/notes/Bouchées gourmandes cerise-chocolat _ Découvrez nos recettes (1).jpg",
//   "herat-name":"Griotte",
//   "heratnote":"/assets/notes/Crème brûlées aux griottes (1).jpg",
//   "base-name":"Vétiver",
//   "basenote":"/assets/notes/What Does Vetiver Smell Like_ The Ultimate Guide _ Dapper Confidential.jpg",
//   },
//   {"id": 25,
//   "name" : "Metalique",
//   "image": "/assets/pr/Tom_Ford_Metallique.jpg",
//   "topnotename":"Poivre rose",
//   "topnote":"/assets/notes/Cet article n'est pas disponible _ Etsy.jpg",
//   "herat-name":"Muguet",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Bois de santal",
//   "basenote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
//   },
//   {"id": 26,
//   "name" : "The one",
//   "image": "/assets/pr/Roll_over_image_to_zoom_in_DOLCE_GABBANA_The_One_for_Men_Eau_de_Parfum_Spray__5_oz_-removebg-preview.jpg",
//   "topnotename":"Basilic",
//   "topnote":"/assets/notes/Bouquet_De_Feuilles_De_Basilic_Doux_Isolé_Sur_Fond_Blanc___Photo_Premium-removebg-preview.jpg",
//   "herat-name":"Fleur d'oranger",
//   "heratnote":"/assets/notes/La_fleur_d_oranger___bienfaits_et_propriétés-removebg-preview.jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
//   {"id": 27,
//   "name" : "Royal night",
//   "image": "/assets/pr/Sexiest_Cologne_For_Men__With_Panty_Dropper_Impact_-removebg-preview.jpg",
//   "topnotename":"Basilic",
//   "topnote":"/assets/notes/Bouquet_De_Feuilles_De_Basilic_Doux_Isolé_Sur_Fond_Blanc___Photo_Premium-removebg-preview.jpg",
//   "herat-name":"Noix de muscade",
//   "heratnote":"/assets/notes/Noix de muscade.jpg",
//   "base-name":"Bois de santal",
//   "basenote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
//   },
//   {"id": 28,
//   "name" : "Initio greatness",
//   "image": "/assets/pr/INITIO_Oud_for_Greatness_eau_de_parfum_90ml-removebg-preview.jpg",
//   "topnotename":"Noix de muscade",
//   "topnote":"/assets/notes/Noix de muscade.jpg",
//   "herat-name":"Réglisse",
//   "heratnote":"/assets/notes/La_Réglisse_et_ses_bienfaits-removebg-preview.jpg",
//   "base-name":"Patchouli",
//   "basenote":"/assets/notes/Patchouli Essential Oil - 1 oz _ Dropper Bottle _ I want to create a blend (add scents to additional comments box below).jpg",
  
//   },
//   {"id": 29,
//   "name" : "Initio happiness",
//   "image": "/assets/pr/Initio_-_.jpg",
//   "topnotename":"Bergamote",
//   "topnote":"/assets/notes/Attract Abundance with Soothing Bergamot (Citrus Bergamia) - Goddess Witchcraft.jpg",
//   "herat-name":"Réglisse",
//   "heratnote":"/assets/notes/La_Réglisse_et_ses_bienfaits-removebg-preview.jpg",
//   "base-name":"Musc",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   },
//   {"id": 30,
//   "name" : "Molecules 02",
//   "image": "/assets/pr/Escentric_Moleculw.jpg",
//   "topnotename":"Jasmine",
//   "topnote":"/assets/notes/581f87d8-87b4-4f4f-8789-aaf78f6a68e4.jpg",
//   "herat-name":"Iso E Super",
//   "heratnote":"/assets/notes/9 Surprising Benefits of Rosewood Essential Oil _ Organic Facts.jpg",
//   "base-name":"Iris",
//   "basenote":"/assets/notes/Rachel_Levy_-_Other_botanicals__2013-2016_-removebg-preview.jpg",
//   },
//   {"id": 31,
//   "name" : "Versace eros",
//   "image": "",
//   "topnotename":"Poivre rose",
//   "topnote":"/assets/notes/Cet article n'est pas disponible _ Etsy.jpg",
//   "herat-name":"Muguet",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Bois de santal",
//   "basenote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
//   },
//   {"id": 32,
//   "name" : "Versace dylan blue",
//   "image": "",
//   "topnotename":"Poivre rose",
//   "topnote":"/assets/notes/Cet article n'est pas disponible _ Etsy.jpg",
//   "herat-name":"Muguet",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Bois de santal",
//   "basenote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
//   },
//   {"id": 33,
//   "name" : "Versace crystal noir",
//   "image": "/assets/pr/12_Gardenia_Perfumes_That_Aren_t_Your_Everyday_Florals-removebg-preview.jpg",
//   "topnotename":"Poivre",
//   "topnote":"/assets/notes/Poivre_noir_entier_IGP_Kampot_-_achat__recettes_et_bienfaits-removebg-preview.jpg",
//   "herat-name":"Ambre",
//   "heratnote":"/assets/notes/Amber-removebg-preview.jpg",
//   "base-name":"Bois de santal",
//   "basenote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
//   },
//   {"id": 34,
//   "name" : "Prada l'homme",
//   "image": "/assets/pr/Prada_Parfums_L_Homme_Prada_L_eau_50_ml__1540_00_____1_l_-removebg-preview.jpg",
//   "topnotename":"Néroli",
//   "topnote":"/assets/notes/Huile essentielle de Néroli _ comment l'utiliser correctement _.jpg",
//   "herat-name":"Géranium",
//   "heratnote":"/assets/notes/New_Seeds_for_2024-removebg-preview.jpg",
//   "base-name":"Bois de santal",
//   "basenote":"/assets/notes/19b9acf2-432e-434f-b105-2f7b84d7608d.jpg",
//   },
//   {"id": 35,
//   "name" : "Prada luna rossa extreme",
//   "image": "/assets/pr/Designer_Clothes__Shoes___Bags_for_Women___SSENSE__1_-removebg-preview.jpg",
//   "topnotename":"Ciste",
//   "topnote":"/assets/notes/Ciste - Cistus _ plantation, floraison et conseils d'entretien.jpg",
//   "herat-name":"Ambre",
//   "heratnote":"/assets/notes/Amber-removebg-preview.jpg",
//   "base-name":"Vanille",
//   "basenote":"/assets/notes/Vanille - Fleurs Comestibles - Épices d'exception.jpg",
//   },
//   {"id": 36,
//   "name" : "Terre d'hermes",
//   "image": "/assets/pr/HERMES_Terre.jpg",
//   "topnotename":"Pamplemousse",
//   "topnote":"/assets/notes/Vinaigrette au pamplemousse (1).jpg",
//   "herat-name":"Poivre",
//   "heratnote":"/assets/notes/Poivre_noir_entier_IGP_Kampot_-_achat__recettes_et_bienfaits-removebg-preview.jpg",
//   "base-name":"Patchouli",
//   "basenote":"/assets/notes/Patchouli Essential Oil - 1 oz _ Dropper Bottle _ I want to create a blend (add scents to additional comments box below).jpg",
//   },
//   {"id": 37,
//   "name" : "Hermes un jardin de monsieur li",
//   "image": "/assets/pr/HERMÈS_Le_Jardi.jpg",
//   "topnotename":"Jasmine",
//   "topnote":"/assets/notes/581f87d8-87b4-4f4f-8789-aaf78f6a68e4.jpg",
//   "herat-name":"Menthe",
//   "heratnote":"/assets/notes/Sirop de menthe maison (1).jpg",
//   "base-name":"Kumquat",
//   "basenote":"/assets/notes/Kumquat - Cure-Naturali_it (1).jpg",
//   },
//   {"id": 38,
//   "name" : "Hermes un jardin sur le toit",
//   "image": "/assets/pr/Hermès_Un_Jardi.jpg",
//   "topnotename":"Magnolia",
//   "topnote":"/assets/notes/Faux Magnolia Blossom Branch 29'' Tall, Large Magnolia Flower Stem, High Quality Real Touch Artificial Silk Flower for Wreath _ Garland - Etsy (1).jpg",
//   "herat-name":"Rose",
//   "heratnote":"/assets/notes/75 Flower Meanings for Every Bouquet Occasion (1).jpg",
//   "base-name":"Poire",
//   "basenote":"/assets/notes/Punch aux fruits sans alcool (1).jpg",
//   },
//   {"id": 39,
//   "name" : "Hermes un jardin sur le mediterranien",
//   "image": "/assets/pr/Hermès_Un_Jardi.jpg",
//   "topnotename":"Lemon",
//   "topnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//   "herat-name":"Fleur d'oranger",
//   "heratnote":"/assets/notes/La_fleur_d_oranger___bienfaits_et_propriétés-removebg-preview.jpg",
//   "base-name":"Musc",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   },
//   {"id": 40,
//   "name" : "hermes un jardin sur la lagune",
//   "image": "/assets/pr/Hermès_Un_Jardin_sur_la_Lagune_.jpg",
//   "topnotename":"Pittosporum",
//   "topnote":"/assets/notes/Summer_Flowers-removebg-preview.jpg",
//   "herat-name":"Magnolia",
//   "heratnote":"/assets/notes/Faux Magnolia Blossom Branch 29'' Tall, Large Magnolia Flower Stem, High Quality Real Touch Artificial Silk Flower for Wreath _ Garland - Etsy (1).jpg",
//   "base-name":"Lys",
//   "basenote":"/assets/notes/Lys _ floraison, taille et entretien (1).jpg",
//   },
//   {"id": 41,
//   "name" : "Voyage d'hermes",
//   "image": "/assets/pr/HERMÈS_Voyage_d_Hermès_Eau_de_Toilette_Beauty___Cosmetics_-_Bloomingdale_s-removebg-preview.jpg",
//   "topnotename":"Limone",
//   "topnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//   "herat-name":"Notes fleuries",
//   "heratnote":"/assets/notes/581f87d8-87b4-4f4f-8789-aaf78f6a68e4.jpg",
//   "base-name":"Musc",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   },
//   {"id": 42,
//   "name" : "Nautica voyage",
//   "image": "/assets/pr/Amazon_com__.jpg",
//   "topnotename":"Pomme",
//   "topnote":"/assets/notes/Pommes Fuji (1).jpg",
//   "herat-name":"Mimosa",
//   "heratnote":"/assets/notes/Mimosas 💛 (1).jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
//   {"id": 43,
//   "name" : "Afternoon swim",
//   "image": "/assets/pr/Ces_parfums_qu.jpg",
//   "topnotename":"Mandarine",
//   "topnote":"/assets/notes/15_Kg_Mandarines_Clementines_NULETA_en_6_malles-removebg-preview.jpg",
//   "herat-name":"Bergamote",
//   "heratnote":"/assets/notes/Attract Abundance with Soothing Bergamot (Citrus Bergamia) - Goddess Witchcraft.jpg",
//   "base-name":"Orange",
//   "basenote":"/assets/notes/Top Foods to Help Lower Cholesterol.jpg",
//   },
//   {"id": 44,
//   "name" : "Louis vuitton l'immensité",
//   "image": "/assets/pr/Products_by_Lo.jpg",
//   "topnotename":"Pamplemousse",
//   "topnote":"/assets/notes/Vinaigrette au pamplemousse (1).jpg",
//   "herat-name":"Géranium",
//   "heratnote":"/assets/notes/New_Seeds_for_2024-removebg-preview.jpg",
//   "base-name":"Ambre",
//   "basenote":"/assets/notes/Amber-removebg-preview.jpg",
//   },
//   {"id": 45,
//   "name" : "Louis vuitton sur la route",
//   "image": "/assets/pr/Nước_Hoa_Loui.jpg",
//   "topnotename":"Lemon",
//   "topnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//   "herat-name":"Noix de muscade",
//   "heratnote":"/assets/notes/Noix de muscade.jpg",
//   "base-name":"Patchouli",
//   "basenote":"/assets/notes/Patchouli Essential Oil - 1 oz _ Dropper Bottle _ I want to create a blend (add scents to additional comments box below).jpg",
//   },
//   {"id": 46,
//   "name" : "Louis vuitton ombre nomade",
//   "image": "/assets/pr/Ombre_Nomade_.jpg",
//   "topnotename":"Poivre noir",
//   "topnote":"/assets/notes/Poivre_noir_entier_IGP_Kampot_-_achat__recettes_et_bienfaits-removebg-preview.jpg",
//   "herat-name":"Safran",
//   "heratnote":"/assets/notes/vus_-removebg-preview.jpg",
//   "base-name":"Rose",
//   "basenote":"/assets/notes/75 Flower Meanings for Every Bouquet Occasion (1).jpg",
//   },
//   {"id": 46,
//   "name" : "Louis vuitton imagination",
//   "image": "/assets/pr/Louis_Vuitton__-_.jpg",
//   "topnotename":"Orange",
//   "topnote":"/assets/notes/Top Foods to Help Lower Cholesterol.jpg",
//   "herat-name":"Cannelle",
//   "heratnote":"/assets/notes/Cannelle___bienfaits__propriétés_et_effets_secondaires-removebg-preview.jpg",
//   "base-name":"Thé noir chinois",
//   "basenote":"/assets/notes/Camellia_Sinensis___Assam_Breakfast_biologique_et_équitable__50_sachets_-removebg-preview.jpg",
//   },
//   {"id": 47,
//   "name" : "Mfk baccarat rouge",
//   "image": "/assets/pr/Maison_Franc.jpg",
//   "topnotename":"Safran",
//   "topnote":"/assets/notes/Fiche_de_culture___Cultivez_votre_propre_safran__Crocus_sativus_-removebg-preview.jpg",
//   "herat-name":"Jasmine",
//   "heratnote":"/assets/notes/581f87d8-87b4-4f4f-8789-aaf78f6a68e4.jpg",
//   "base-name":"Musk",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   },
//   {"id": 48,
//   "name" : "Mfk petit matin",
//   "image": "/assets/pr/Maison_Francis_K.jpg",
//   "topnotename":"Lemon",
//   "topnote":"/assets/notes/Super Easy Lemon Bars_ New & improved with only 5 simple ingredients! (1).jpg",
//   "herat-name":"Lavender",
//   "heratnote":"/assets/notes/2007_04_07_Une_fleur_de_jacinthe-removebg-preview.jpg",
//   "base-name":"Musk",
//   "basenote":"/assets/notes/91b7d907-011d-46e9-9c96-3a76743ff6b9.jpg",
//   }
// ]

}
